DROP TABLE IF EXISTS JOURNAL CASCADE;
DROP SEQUENCE IF EXISTS SEQ_JOURNAL;

DROP TABLE IF EXISTS PAPER CASCADE;
DROP SEQUENCE IF EXISTS SEQ_PAPER;

CREATE SEQUENCE SEQ_JOURNAL;
CREATE SEQUENCE SEQ_PAPER;

CREATE TABLE JOURNAL
(ID         NUMERIC(5,0)
   CONSTRAINT JOURNAL_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR(256) 
   CONSTRAINT JOURNAL_NOME_NN
   NOT NULL,
  VOLUME          INT
   CONSTRAINT JOURNAL_VOLUME_NN
   NOT NULL,
  VALOR        float
   CONSTRAINT JOURNAL_VALOR_NN
   NOT NULL);

INSERT INTO JOURNAL(ID, NOME, VOLUME, VALOR)
VALUES(NEXTVAL('SEQ_JOURNAL'), 'Pattern Recognition', 76, 128.00);

INSERT INTO JOURNAL(ID, NOME, VOLUME, VALOR)
VALUES(NEXTVAL('SEQ_JOURNAL'), 'Data & Knowledge Engineering', 112, 0);

INSERT INTO JOURNAL(ID, NOME, VOLUME, VALOR)
VALUES(NEXTVAL('SEQ_JOURNAL'), 'Neurocomputing', 274, 128.00);

INSERT INTO JOURNAL(ID, NOME, VOLUME, VALOR)
VALUES(NEXTVAL('SEQ_JOURNAL'), 'Pattern Recognition Letters', 101, 0);

CREATE TABLE PAPER
(ID         NUMERIC(5,0)
   CONSTRAINT PAPER_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR(256) 
   CONSTRAINT PAPER_NOME_NN
   NOT NULL,
 VALOR        float
   CONSTRAINT PAPER_VALOR_NN
   NOT NULL,
 JOURNAL_ID   NUMERIC(5,0)
   CONSTRAINT JOURNAL_FK_NN
   REFERENCES JOURNAL(ID)
   CONSTRAINT PAPER_JOURNAL_ID_NN
   NOT NULL);


INSERT INTO PAPER(ID, NOME, VALOR, JOURNAL_ID)
VALUES(NEXTVAL('SEQ_PAPER'), 'Virtual dictionary based kernel sparse representation for face recognition', 35.95, 1);

INSERT INTO PAPER(ID, NOME, VALOR, JOURNAL_ID)
VALUES(NEXTVAL('SEQ_PAPER'), 'A modified convolutional neural network for face sketch synthesis', 35.95, 1);

INSERT INTO PAPER(ID, NOME, VALOR, JOURNAL_ID)
VALUES(NEXTVAL('SEQ_PAPER'), 'Frequent patterns in ETL workflows: An empirical approach', 0, 2);

INSERT INTO PAPER(ID, NOME, VALOR, JOURNAL_ID)
VALUES(NEXTVAL('SEQ_PAPER'), 'Query completion in community-based Question Answering search', 35.95, 3);

INSERT INTO PAPER(ID, NOME, VALOR, JOURNAL_ID)
VALUES(NEXTVAL('SEQ_PAPER'), 'Recurrent convolutional neural network for answer selection in community question answering', 35.95, 3);

COMMIT;
